version: 2
jobs:
  build:
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: Check versions
          command: |
            node -v
            npm -v
      # - run:
      #     name: Update npm
      #     command: 'sudo npm install -g npm@latest'
      # - run:
      #     name: configure npm for private modules
      #     command: |
      #       npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      #       npm whoami
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: compile typescript
          command: |
            npm run clean
            npm run build
  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: run npm test
          command: npm test
      # - run:
      #     name: Generate code coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
  doc:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Generate docs
          command: |
            npm run build
            npm run doc
  deploy2development:
    docker:
      - image: circleci/node:8.10
    #   - image: google/cloud-sdk
    steps:
      - checkout
      # - run:
      #     name: Set NPM_TOKEN
      #     command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: compile typescript
          command: |
            npm run build
      - run:
          name: Install Serverless CLI
          command: |
            sudo npm i -g serverless
      - run:
          name: Deploy application
          command: serverless deploy --force --stage dev -v
  deploy:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: compile typescript
          command: |
            npm run build
      - run:
          name: Install Serverless CLI
          command: |
            sudo npm i -g serverless
      - run:
          name: Deploy application
          command: serverless deploy --force --stage prod -v
# Used for orchestrating all jobs.
workflows:
  version: 2

  build-test-doc-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - doc:
          requires:
            - test
      - deploy2development:
          requires:
            - doc
          filters:
            branches:
              only: develop
      - deploy:
          requires:
            - doc
          filters:
            branches:
              only: master
